Add addNewItem button
JanekJaniak/GastroFoodcostVue pull request #7
Opened 2020-11-04 17:23 UTC by JanekJaniak

2020-11-04 19:06 UTC, jan-gajdowicz requested changes
2 minor things

2020-11-04 19:06 UTC, jan-gajdowicz commented on src/components/RenderList.vue
> +            <strong>Gross Value:{{calculateGrossValue(ingredient.quantity,ingredient.price,ingredient.vat)}}</strong>
use spaces between arguments

2020-11-04 19:06 UTC, jan-gajdowicz commented on src/components/RenderList.vue
> -        console.log(this.value);
Remove unused method

2020-11-04 19:07 UTC, JanekJaniak commented on src/components/RenderList.vue
> +            <strong>Gross Value:{{calculateGrossValue(ingredient.quantity,ingredient.price,ingredient.vat)}}</strong>
✔️

2020-11-05 12:48 UTC, JanekJaniak commented on src/components/RenderList.vue
> -        console.log(this.value);
✔️

2020-11-05 12:51 UTC, merged